### ISSUE TITLE
formatter setting is ignored

### ISSUE THREAD

**Issue by dmitry-saritasa** [brunch/eslint-brunch#21]
### vesions
```
"eslint-brunch": "^3.12.0",
(crm) ➜  backend git:(develop) ✗ eslint --version
v3.14.0
(crm) ➜  backend git:(develop) ✗ brunch --version         
2.10.10

```
### console output
```
16:20:18 - info: Reloading watcher...
16:20:23 - info: application started on http://localhost:3333/
16:20:23 - info: compiling
16:20:26 - error: Linting of frontend/js/config.js failed. Error: ESLint reported:
   
   /home/dmitry/Projects/crm/backend/frontend/js/config.js
     4:5  error  Parsing error: Unexpected token common
   
   ✖ 1 problem (1 error, 0 warnings)
   

/home/dmitry/Projects/crm/backend/frontend/js/config.js
  4:5  error  Parsing error: Unexpected token common

✖ 1 problem (1 error, 0 warnings)

    at error (/home/dmitry/Projects/crm/backend/node_modules/brunch/lib/fs_utils/pipeline.js:16:13)
    at Promise.all.catch.error (/home/dmitry/Projects/crm/backend/node_modules/brunch/lib/fs_utils/pipeline.js:36:25)
 
16:20:26 - error: Linting of frontend/js/index.js failed. Error: ESLint reported:
   
   /home/dmitry/Projects/crm/backend/frontend/js/index.js
     1:1  error  Use the global form of 'use strict'                            strict
     1:1  error  Move the invocation into the parens that contain the function  wrap-iife
   
   ✖ 2 problems (2 errors, 0 warnings)
   

/home/dmitry/Projects/crm/backend/frontend/js/index.js
  1:1  error  Use the global form of 'use strict'                            strict
  1:1  error  Move the invocation into the parens that contain the function  wrap-iife

✖ 2 problems (2 errors, 0 warnings)

    at error (/home/dmitry/Projects/crm/backend/node_modules/brunch/lib/fs_utils/pipeline.js:16:13)
    at Promise.all.catch.error (/home/dmitry/Projects/crm/backend/node_modules/brunch/lib/fs_utils/pipeline.js:36:25)
 
16:20:26 - info: compiled 26 files into 3 files, copied 8 in 7.4 sec
04 Oct 16:20:26 - info: [copycat] copied 6 files (0 files were not modified)
04 Oct 16:20:26 - info: [copycat] copied .frontend/fonts/FontAwesome.otf
04 Oct 16:20:26 - info: [copycat] copied .frontend/fonts/fontawesome-webfont.eot
04 Oct 16:20:26 - info: [copycat] copied .frontend/fonts/fontawesome-webfont.svg
04 Oct 16:20:26 - info: [copycat] copied .frontend/fonts/fontawesome-webfont.ttf
04 Oct 16:20:26 - info: [copycat] copied .frontend/fonts/fontawesome-webfont.woff
04 Oct 16:20:26 - info: [copycat] copied .frontend/fonts/fontawesome-webfont.woff2
```

whatever I put inside the formatter, it always gives me the same effect in output of **brunch watch --server**

```
eslint: {
    pattern: /^frontend\/.*\.js?$/,
    warnOnly: false,
    formatter: 'table'
  }
```

**Comment by shvaikalesh** [comment]
Hey @dmitry-saritasa, thanks for issue. We haven't released the plugin with `formatter` yet. Use it from `master` for now.
